
MAKE := make --no-print-directory

all :
	@$(MAKE) -f log4cplusS_demo_makefile_debug clean;
	@$(MAKE) -f log4cplusS_demo_makefile_debug;
	@$(MAKE) -f log4cplusS_demo_makefile_debug clean;

	@$(MAKE) -f log4cplusS_demo_makefile_release clean;
	@$(MAKE) -f log4cplusS_demo_makefile_release;
	@$(MAKE) -f log4cplusS_demo_makefile_release clean;

	@$(MAKE) -f log4cplusWapperS_demo_makefile_debug clean;
	@$(MAKE) -f log4cplusWapperS_demo_makefile_debug;
	@$(MAKE) -f log4cplusWapperS_demo_makefile_debug clean;

	@$(MAKE) -f log4cplusWapperS_demo_makefile_release clean;
	@$(MAKE) -f log4cplusWapperS_demo_makefile_release;
	@$(MAKE) -f log4cplusWapperS_demo_makefile_release clean;



